version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: news-scraper-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - news-scraper-network

volumes:
  redis_data:
    driver: local

networks:
  news-scraper-network:
    driver: bridge
