version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: news-scraper-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - news-scraper-api
    restart: unless-stopped
    networks:
      - news-scraper-network

  news-scraper-api:
    image: news-scraper-api:latest
    container_name: news-scraper-api
    expose:
      - "8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
      - LOG_LEVEL=INFO
    networks:
      - news-scraper-network

networks:
  news-scraper-network:
    driver: bridge
